[theme]
primaryColor = "#9C27B0"  # Deep vibrant purple  
backgroundColor = "#0D0B14"  # Almost black with a hint of violet  
secondaryBackgroundColor = "#21162E"  # Dark muted violet for sidebar contrast  
textColor = "#FFFFFF"  # White text for both chat and sidebar  
font = "sans serif"
